### ISSUE TITLE
A bug about Safari

### ISSUE THREAD

**Issue by shangmuzhuqin** [MiraHikari/portfolio#1]
The page is great, but there seems to be a minor bug. When using the Safari browser, the image box tends to stretch out excessively long. I managed to fix it with a simple solution.
`<div class="relative overflow-hidden rounded-lg border border-skin-hue/20 bg-skin-button-accent/20" style="height: 0; padding-bottom: 100%;">`

![image](https://github.com/user-attachments/assets/6cfa4294-787e-4e66-8e4e-211537c4c0c5)

**Comment by MiraHikari** [comment]
Thank you for your issue, the code fix will be submitted shortly.
